services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  api:
    build: .
    container_name: fastapi-application
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_user: root
      MYSQL_password: root
      MYSQL_database: digital_hunter
    ports:
      - '8000:8000'


volumes:
  mysql_data:
